### ISSUE TITLE
Migrate API to V2

### ISSUE THREAD

**Issue by snowman** [Garulf/TenorGIF#11]
see [How to migrate from Tenor's V1 API](https://developers.google.com/tenor/guides/migrate-from-v1)

**Comment by OnAllTwos** [comment]
I made a pr with an update to the V2 api. 

https://github.com/Garulf/TenorGIF/pull/13

**Comment by Garulf** [comment]
This is fixed by https://github.com/Garulf/TenorGIF/pull/13

Thanks @gamebuilder116
