### ISSUE TITLE
Partial Fix for Tenor Gif API V2

### ISSUE THREAD

**Issue by astroboii47** [Garulf/TenorGIF#9]
Been working on updating this for the new Tenor API, but stuck on switching from reading an array of dictionaries to just reading a dictionary directly (sorry not super familiar with github pull requests or python)

I replaced flox and the flox library with the latest 0.18.0 version and updated the base url in helper.py to the new "https://tenor.googleapis.com/v2", which now loads trending searches correctly: 
![Snipaste_2022-12-27_15-46-26](https://user-images.githubusercontent.com/58410541/209612531-ac00be5f-83f5-4964-ba05-c68dbe19dd99.png)

There is still an error when searching, which I assume is linked to the changes in the V2 api listed here
![Snipaste_2022-12-27_15-47-39](https://user-images.githubusercontent.com/58410541/209612663-a4ba6620-25ff-45c8-a520-ff9f7fd30b63.png)

Maybe someone else who is more versed in python can take a look at the changes from GIF_FORMAT : MEDIA OBJECT to CONTENT_FORMAT : MEDIA OBJECT as listed in these two pages
API v1: https://tenor.com/gifapi/documentation#responseobjects-gif
API v2: https://developers.google.com/tenor/guides/response-objects-and-errors#response-object

Hoping that can solve it and we can revive this plugin :)

**Comment by Garulf** [comment]
This is fixed by https://github.com/Garulf/TenorGIF/pull/13

Thanks @gamebuilder116
